### PR TITLE
Correct issues in setup.py.mustache

### LINKED ISSUE #12: setup.py depends on wrong grpc
In particular, it depends on a package named grpc, whereas the appropriate gRPC library is called grpcio.

### PR DESCRIPTION
**Pull request by nathanielmanistaatgoogle**
@soltanmm and @pcostell, please also review.

Fixes #12 and #13.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
LGTM, please merge once the others have taken a look.

**Comment by pcostell** [comment]
LGTM

**Comment by tbetbetbe** [comment]
@soltanmm, I'm happy to merge once you LGTM

**Comment by tbetbetbe** [comment]
Am merging now, if additional changes are needed, they can go in another PR :)

**Pull request merged**
